export const AFRICASTALKING_API_KEY = process.env.AFRICASTALKING_API_KEY;
export const AFRICASTALKING_USERNAME = process.env.AFRICASTALKING_USERNAME;
export const AFRICASTALKING_FROM = process.env.AFRICASTALKING_FROM;
